name: Deploy

on:
  workflow_dispatch:
    inputs:
      artifact-name:
        required: true
      stack:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:

      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_CICD_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Download
        run: |
          aws s3 cp ${{ vars.ARTIFACT_BUCKET }}${{ github.event.inputs.artifact-name }} .

      - name: Unpack
        run: |
          tar -xzf ${{ github.event.inputs.artifact-name }}

      - name: Deploy
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'deploy'
          cdk_stack: ${{ github.event.inputs.stack }}
