name: Push to Production

on:
  workflow_dispatch:
    inputs:
      version:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3
        token: ${{ github.event.inputs.version }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: |
          cd $GITHUB_WORKSPACE
          # Python
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          # NodeJS
          cd frontend
          npm ci

      - name: Build CDN Stack
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'deploy'
          cdk_stack: 'cdn-prod'
          cdk_args: '--context domain_name=${{ vars.DEPLOYMENT_DOMAIN_NAME }} --context environment=prod --exclusively'

      - name: Build Main Stack
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'deploy'
          cdk_stack: 'main-prod'
          cdk_args: '--context domain_name=${{ vars.DEPLOYMENT_DOMAIN_NAME }} --context environment=prod --exclusively --context localhost_access=true'

      - name: Configure Amplify
        run: |
          python stack/create_amplify_config.py prod ${{ vars.AWS_REGION }} ${{ vars.DEPLOYMENT_DOMAIN_NAME }}

      - name: Build Frontend
        run: |
          cd frontend
          npm run build

      - name: Build Frontend Deployment Stack
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'deploy'
          cdk_stack: 'frontend-deployment-prod'
          cdk_args: '--context domain_name=${{ vars.DEPLOYMENT_DOMAIN_NAME }} --context environment=prod --exclusively'
